# a wrapper to FindPkgConfig that, depending on the variable ${XCVL_SUITE} uses
# FindPkgConfig (XCVL_SUITE == FALSE) or the internal mechanisms of cmake to
# link to a xcvl provided library.

INCLUDE(FindPkgConfig)

MACRO(FIND_XCVL_LIBRARY PREFIX LIBRARY_NAME)

	IF(NOT XCVL_SUITE)
                PKG_CHECK_MODULES(${PREFIX} ${LIBRARY_NAME})
                MESSAGE(STATUS "USING PKG_CHECK_MODULES")
	ELSE(NOT XCVL_SUITE)
		GET_PROPERTY(XCVL_PROJECT_INCLUDE_DIRECTOTRIES DIRECTORY ${CMAKE_SOURCE_DIR}/${LIBRARY_NAME}/src PROPERTY INCLUDE_DIRECTORIES)
		SET(${PREFIX}_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/${LIBRARY_NAME}/src ${XCVL_PROJECT_INCLUDE_DIRECTOTRIES})
		SET(${PREFIX}_INCLUDE_DIRS ${CMAKE_SOURCE_DIR}/build/${LIBRARY_NAME}/src ${XCVL_PROJECT_INCLUDE_DIRECTOTRIES})
		SET(${PREFIX}_LIBRARIES ${LIBRARY_NAME})
	ENDIF(NOT XCVL_SUITE)

ENDMACRO(FIND_XCVL_LIBRARY)
